### ISSUE TITLE
Проблема с owl-carousel [ошибка путей]

### ISSUE THREAD

**Issue by dmitr1y** [sevenns/e-detective#4]
`
bower owl-carousel#^1.3.2               ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/OwlFonk/OwlCarousel.git", exit code of #128 remote: Invalid username or password. fatal: Authentication failed for 'https://github.com/OwlFonk/OwlCarousel.git/'
`
Репозитория **https://github.com/OwlFonk/OwlCarousel.git** больше не существует. После выхода 2 версии репозитория стал **https://github.com/OwlCarousel2/OwlCarousel2** и, соответсвенно, пути также изменились

**Comment by sevenns** [comment]
Прошу прощения за столь долгое млчание, не сразу заметил, да и с временем не особо. Поправил. Теперь owl2 используется. Проверьте.

Проект старый. Доделываться вряд ли будет. Также возможно в скором исчезнет с гитхаба, так сохраните на всякий, если что-то от туда захотите взять. ;)
